### ISSUE TITLE
There appears to be a line order error in index.js

### ISSUE THREAD

**Issue by lanmower** [hyperswarm/dht#44]
There was an uncaught error ReferenceError: Cannot access 'error' before initialization
    at Timeout.ontimeout [as _onTimeout] (C:\app\dev\test\node_modules\@hyperswarm\dht\index.js:216:7)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)

**Comment by 4c656554** [comment]
I get this too, with slightly different line numbers:

```
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
```
